//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Clay__ScrollContainerDataInternal : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Clay__ScrollContainerDataInternal(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Clay__ScrollContainerDataInternal obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Clay__ScrollContainerDataInternal obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Clay__ScrollContainerDataInternal() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ClayLibraryPINVOKE.delete_Clay__ScrollContainerDataInternal(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Clay_LayoutElement layoutElement {
    set {
      ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_layoutElement_set(swigCPtr, Clay_LayoutElement.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_layoutElement_get(swigCPtr);
      Clay_LayoutElement ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_LayoutElement(cPtr, false);
      return ret;
    } 
  }

  public Clay_BoundingBox boundingBox {
    set {
      ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_boundingBox_set(swigCPtr, Clay_BoundingBox.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_boundingBox_get(swigCPtr);
      Clay_BoundingBox ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_BoundingBox(cPtr, false);
      return ret;
    } 
  }

  public Clay_Dimensions contentSize {
    set {
      ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_contentSize_set(swigCPtr, Clay_Dimensions.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_contentSize_get(swigCPtr);
      Clay_Dimensions ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_Dimensions(cPtr, false);
      return ret;
    } 
  }

  public Clay_Vector2 scrollOrigin {
    set {
      ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_scrollOrigin_set(swigCPtr, Clay_Vector2.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_scrollOrigin_get(swigCPtr);
      Clay_Vector2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_Vector2(cPtr, false);
      return ret;
    } 
  }

  public Clay_Vector2 pointerOrigin {
    set {
      ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_pointerOrigin_set(swigCPtr, Clay_Vector2.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_pointerOrigin_get(swigCPtr);
      Clay_Vector2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_Vector2(cPtr, false);
      return ret;
    } 
  }

  public Clay_Vector2 scrollMomentum {
    set {
      ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_scrollMomentum_set(swigCPtr, Clay_Vector2.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_scrollMomentum_get(swigCPtr);
      Clay_Vector2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_Vector2(cPtr, false);
      return ret;
    } 
  }

  public Clay_Vector2 scrollPosition {
    set {
      ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_scrollPosition_set(swigCPtr, Clay_Vector2.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_scrollPosition_get(swigCPtr);
      Clay_Vector2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_Vector2(cPtr, false);
      return ret;
    } 
  }

  public Clay_Vector2 previousDelta {
    set {
      ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_previousDelta_set(swigCPtr, Clay_Vector2.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_previousDelta_get(swigCPtr);
      Clay_Vector2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_Vector2(cPtr, false);
      return ret;
    } 
  }

  public float momentumTime {
    set {
      ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_momentumTime_set(swigCPtr, value);
    } 
    get {
      float ret = ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_momentumTime_get(swigCPtr);
      return ret;
    } 
  }

  public uint elementId {
    set {
      ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_elementId_set(swigCPtr, value);
    } 
    get {
      uint ret = ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_elementId_get(swigCPtr);
      return ret;
    } 
  }

  public bool openThisFrame {
    set {
      ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_openThisFrame_set(swigCPtr, value);
    } 
    get {
      bool ret = ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_openThisFrame_get(swigCPtr);
      return ret;
    } 
  }

  public bool pointerScrollActive {
    set {
      ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_pointerScrollActive_set(swigCPtr, value);
    } 
    get {
      bool ret = ClayLibraryPINVOKE.Clay__ScrollContainerDataInternal_pointerScrollActive_get(swigCPtr);
      return ret;
    } 
  }

  public Clay__ScrollContainerDataInternal() : this(ClayLibraryPINVOKE.new_Clay__ScrollContainerDataInternal(), true) {
  }

}
