//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Clay_BooleanWarnings : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Clay_BooleanWarnings(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Clay_BooleanWarnings obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Clay_BooleanWarnings obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Clay_BooleanWarnings() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ClayLibraryPINVOKE.delete_Clay_BooleanWarnings(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public bool maxElementsExceeded {
    set {
      ClayLibraryPINVOKE.Clay_BooleanWarnings_maxElementsExceeded_set(swigCPtr, value);
    } 
    get {
      bool ret = ClayLibraryPINVOKE.Clay_BooleanWarnings_maxElementsExceeded_get(swigCPtr);
      return ret;
    } 
  }

  public bool maxRenderCommandsExceeded {
    set {
      ClayLibraryPINVOKE.Clay_BooleanWarnings_maxRenderCommandsExceeded_set(swigCPtr, value);
    } 
    get {
      bool ret = ClayLibraryPINVOKE.Clay_BooleanWarnings_maxRenderCommandsExceeded_get(swigCPtr);
      return ret;
    } 
  }

  public bool maxStringMeasureCacheExceeded {
    set {
      ClayLibraryPINVOKE.Clay_BooleanWarnings_maxStringMeasureCacheExceeded_set(swigCPtr, value);
    } 
    get {
      bool ret = ClayLibraryPINVOKE.Clay_BooleanWarnings_maxStringMeasureCacheExceeded_get(swigCPtr);
      return ret;
    } 
  }

  public Clay_BooleanWarnings() : this(ClayLibraryPINVOKE.new_Clay_BooleanWarnings(), true) {
  }

}
