//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Clay_Arena : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Clay_Arena(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Clay_Arena obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Clay_Arena obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Clay_Arena() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ClayLibraryPINVOKE.delete_Clay_Arena(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Clay_String label {
    set {
      ClayLibraryPINVOKE.Clay_Arena_label_set(swigCPtr, Clay_String.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay_Arena_label_get(swigCPtr);
      Clay_String ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_String(cPtr, false);
      return ret;
    } 
  }

  public ulong nextAllocation {
    set {
      ClayLibraryPINVOKE.Clay_Arena_nextAllocation_set(swigCPtr, value);
    } 
    get {
      ulong ret = ClayLibraryPINVOKE.Clay_Arena_nextAllocation_get(swigCPtr);
      return ret;
    } 
  }

  public ulong capacity {
    set {
      ClayLibraryPINVOKE.Clay_Arena_capacity_set(swigCPtr, value);
    } 
    get {
      ulong ret = ClayLibraryPINVOKE.Clay_Arena_capacity_get(swigCPtr);
      return ret;
    } 
  }

  public string memory {
    set {
      ClayLibraryPINVOKE.Clay_Arena_memory_set(swigCPtr, value);
    } 
    get {
      string ret = ClayLibraryPINVOKE.Clay_Arena_memory_get(swigCPtr);
      return ret;
    } 
  }

  public Clay_Arena() : this(ClayLibraryPINVOKE.new_Clay_Arena(), true) {
  }

}
