//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Clay__MeasureTextCacheItem : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Clay__MeasureTextCacheItem(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Clay__MeasureTextCacheItem obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Clay__MeasureTextCacheItem obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Clay__MeasureTextCacheItem() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ClayLibraryPINVOKE.delete_Clay__MeasureTextCacheItem(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Clay_Dimensions unwrappedDimensions {
    set {
      ClayLibraryPINVOKE.Clay__MeasureTextCacheItem_unwrappedDimensions_set(swigCPtr, Clay_Dimensions.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay__MeasureTextCacheItem_unwrappedDimensions_get(swigCPtr);
      Clay_Dimensions ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_Dimensions(cPtr, false);
      return ret;
    } 
  }

  public int measuredWordsStartIndex {
    set {
      ClayLibraryPINVOKE.Clay__MeasureTextCacheItem_measuredWordsStartIndex_set(swigCPtr, value);
    } 
    get {
      int ret = ClayLibraryPINVOKE.Clay__MeasureTextCacheItem_measuredWordsStartIndex_get(swigCPtr);
      return ret;
    } 
  }

  public uint id {
    set {
      ClayLibraryPINVOKE.Clay__MeasureTextCacheItem_id_set(swigCPtr, value);
    } 
    get {
      uint ret = ClayLibraryPINVOKE.Clay__MeasureTextCacheItem_id_get(swigCPtr);
      return ret;
    } 
  }

  public int nextIndex {
    set {
      ClayLibraryPINVOKE.Clay__MeasureTextCacheItem_nextIndex_set(swigCPtr, value);
    } 
    get {
      int ret = ClayLibraryPINVOKE.Clay__MeasureTextCacheItem_nextIndex_get(swigCPtr);
      return ret;
    } 
  }

  public uint generation {
    set {
      ClayLibraryPINVOKE.Clay__MeasureTextCacheItem_generation_set(swigCPtr, value);
    } 
    get {
      uint ret = ClayLibraryPINVOKE.Clay__MeasureTextCacheItem_generation_get(swigCPtr);
      return ret;
    } 
  }

  public Clay__MeasureTextCacheItem() : this(ClayLibraryPINVOKE.new_Clay__MeasureTextCacheItem(), true) {
  }

}
