//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum Clay_PointerCaptureMode {
  CLAY_POINTER_CAPTURE_MODE_CAPTURE,
  CLAY_POINTER_CAPTURE_MODE_PASSTHROUGH
}
