//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Clay_Color : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Clay_Color(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Clay_Color obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Clay_Color obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Clay_Color() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ClayLibraryPINVOKE.delete_Clay_Color(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public float r {
    set {
      ClayLibraryPINVOKE.Clay_Color_r_set(swigCPtr, value);
    } 
    get {
      float ret = ClayLibraryPINVOKE.Clay_Color_r_get(swigCPtr);
      return ret;
    } 
  }

  public float g {
    set {
      ClayLibraryPINVOKE.Clay_Color_g_set(swigCPtr, value);
    } 
    get {
      float ret = ClayLibraryPINVOKE.Clay_Color_g_get(swigCPtr);
      return ret;
    } 
  }

  public float b {
    set {
      ClayLibraryPINVOKE.Clay_Color_b_set(swigCPtr, value);
    } 
    get {
      float ret = ClayLibraryPINVOKE.Clay_Color_b_get(swigCPtr);
      return ret;
    } 
  }

  public float a {
    set {
      ClayLibraryPINVOKE.Clay_Color_a_set(swigCPtr, value);
    } 
    get {
      float ret = ClayLibraryPINVOKE.Clay_Color_a_get(swigCPtr);
      return ret;
    } 
  }

  public Clay_Color() : this(ClayLibraryPINVOKE.new_Clay_Color(), true) {
  }

}
