//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum Clay__ElementConfigType : byte {
  CLAY__ELEMENT_CONFIG_TYPE_RECTANGLE = 1,
  CLAY__ELEMENT_CONFIG_TYPE_BORDER_CONTAINER = 2,
  CLAY__ELEMENT_CONFIG_TYPE_FLOATING_CONTAINER = 4,
  CLAY__ELEMENT_CONFIG_TYPE_SCROLL_CONTAINER = 8,
  CLAY__ELEMENT_CONFIG_TYPE_IMAGE = 16,
  CLAY__ELEMENT_CONFIG_TYPE_TEXT = 32,
  CLAY__ELEMENT_CONFIG_TYPE_CUSTOM = 64
}
