//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum Clay__SizingType : byte {
  CLAY__SIZING_TYPE_FIT,
  CLAY__SIZING_TYPE_GROW,
  CLAY__SIZING_TYPE_PERCENT,
  CLAY__SIZING_TYPE_FIXED
}
