//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Clay_LayoutElement : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Clay_LayoutElement(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Clay_LayoutElement obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Clay_LayoutElement obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Clay_LayoutElement() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ClayLibraryPINVOKE.delete_Clay_LayoutElement(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Clay__LayoutElementChildren children {
    set {
      ClayLibraryPINVOKE.Clay_LayoutElement_children_set(swigCPtr, Clay__LayoutElementChildren.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay_LayoutElement_children_get(swigCPtr);
      Clay__LayoutElementChildren ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay__LayoutElementChildren(cPtr, false);
      return ret;
    } 
  }

  public Clay__TextElementData textElementData {
    set {
      ClayLibraryPINVOKE.Clay_LayoutElement_textElementData_set(swigCPtr, Clay__TextElementData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay_LayoutElement_textElementData_get(swigCPtr);
      Clay__TextElementData ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay__TextElementData(cPtr, false);
      return ret;
    } 
  }

  public Clay_Dimensions dimensions {
    set {
      ClayLibraryPINVOKE.Clay_LayoutElement_dimensions_set(swigCPtr, Clay_Dimensions.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay_LayoutElement_dimensions_get(swigCPtr);
      Clay_Dimensions ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_Dimensions(cPtr, false);
      return ret;
    } 
  }

  public Clay_Dimensions minDimensions {
    set {
      ClayLibraryPINVOKE.Clay_LayoutElement_minDimensions_set(swigCPtr, Clay_Dimensions.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay_LayoutElement_minDimensions_get(swigCPtr);
      Clay_Dimensions ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_Dimensions(cPtr, false);
      return ret;
    } 
  }

  public Clay_LayoutConfig layoutConfig {
    set {
      ClayLibraryPINVOKE.Clay_LayoutElement_layoutConfig_set(swigCPtr, Clay_LayoutConfig.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay_LayoutElement_layoutConfig_get(swigCPtr);
      Clay_LayoutConfig ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_LayoutConfig(cPtr, false);
      return ret;
    } 
  }

  public Clay__ElementConfigArraySlice elementConfigs {
    set {
      ClayLibraryPINVOKE.Clay_LayoutElement_elementConfigs_set(swigCPtr, Clay__ElementConfigArraySlice.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay_LayoutElement_elementConfigs_get(swigCPtr);
      Clay__ElementConfigArraySlice ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay__ElementConfigArraySlice(cPtr, false);
      return ret;
    } 
  }

  public uint configsEnabled {
    set {
      ClayLibraryPINVOKE.Clay_LayoutElement_configsEnabled_set(swigCPtr, value);
    } 
    get {
      uint ret = ClayLibraryPINVOKE.Clay_LayoutElement_configsEnabled_get(swigCPtr);
      return ret;
    } 
  }

  public uint id {
    set {
      ClayLibraryPINVOKE.Clay_LayoutElement_id_set(swigCPtr, value);
    } 
    get {
      uint ret = ClayLibraryPINVOKE.Clay_LayoutElement_id_get(swigCPtr);
      return ret;
    } 
  }

  public Clay_LayoutElement() : this(ClayLibraryPINVOKE.new_Clay_LayoutElement(), true) {
  }

}
