//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Clay_RenderCommand : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Clay_RenderCommand(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Clay_RenderCommand obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Clay_RenderCommand obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Clay_RenderCommand() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ClayLibraryPINVOKE.delete_Clay_RenderCommand(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Clay_BoundingBox boundingBox {
    set {
      ClayLibraryPINVOKE.Clay_RenderCommand_boundingBox_set(swigCPtr, Clay_BoundingBox.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay_RenderCommand_boundingBox_get(swigCPtr);
      Clay_BoundingBox ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_BoundingBox(cPtr, false);
      return ret;
    } 
  }

  public Clay_ElementConfigUnion config {
    set {
      ClayLibraryPINVOKE.Clay_RenderCommand_config_set(swigCPtr, Clay_ElementConfigUnion.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay_RenderCommand_config_get(swigCPtr);
      Clay_ElementConfigUnion ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_ElementConfigUnion(cPtr, false);
      return ret;
    } 
  }

  public Clay_String text {
    set {
      ClayLibraryPINVOKE.Clay_RenderCommand_text_set(swigCPtr, Clay_String.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay_RenderCommand_text_get(swigCPtr);
      Clay_String ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_String(cPtr, false);
      return ret;
    } 
  }

  public uint id {
    set {
      ClayLibraryPINVOKE.Clay_RenderCommand_id_set(swigCPtr, value);
    } 
    get {
      uint ret = ClayLibraryPINVOKE.Clay_RenderCommand_id_get(swigCPtr);
      return ret;
    } 
  }

  public Clay_RenderCommandType commandType {
    set {
      ClayLibraryPINVOKE.Clay_RenderCommand_commandType_set(swigCPtr, (int)value);
    } 
    get {
      Clay_RenderCommandType ret = (Clay_RenderCommandType)ClayLibraryPINVOKE.Clay_RenderCommand_commandType_get(swigCPtr);
      return ret;
    } 
  }

  public Clay_RenderCommand() : this(ClayLibraryPINVOKE.new_Clay_RenderCommand(), true) {
  }

}
