//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Clay_LayoutConfig : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Clay_LayoutConfig(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Clay_LayoutConfig obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Clay_LayoutConfig obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Clay_LayoutConfig() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ClayLibraryPINVOKE.delete_Clay_LayoutConfig(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Clay_Sizing sizing {
    set {
      ClayLibraryPINVOKE.Clay_LayoutConfig_sizing_set(swigCPtr, Clay_Sizing.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay_LayoutConfig_sizing_get(swigCPtr);
      Clay_Sizing ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_Sizing(cPtr, false);
      return ret;
    } 
  }

  public Clay_Padding padding {
    set {
      ClayLibraryPINVOKE.Clay_LayoutConfig_padding_set(swigCPtr, Clay_Padding.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay_LayoutConfig_padding_get(swigCPtr);
      Clay_Padding ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_Padding(cPtr, false);
      return ret;
    } 
  }

  public ushort childGap {
    set {
      ClayLibraryPINVOKE.Clay_LayoutConfig_childGap_set(swigCPtr, value);
    } 
    get {
      ushort ret = ClayLibraryPINVOKE.Clay_LayoutConfig_childGap_get(swigCPtr);
      return ret;
    } 
  }

  public Clay_ChildAlignment childAlignment {
    set {
      ClayLibraryPINVOKE.Clay_LayoutConfig_childAlignment_set(swigCPtr, Clay_ChildAlignment.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay_LayoutConfig_childAlignment_get(swigCPtr);
      Clay_ChildAlignment ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_ChildAlignment(cPtr, false);
      return ret;
    } 
  }

  public Clay_LayoutDirection layoutDirection {
    set {
      ClayLibraryPINVOKE.Clay_LayoutConfig_layoutDirection_set(swigCPtr, (int)value);
    } 
    get {
      Clay_LayoutDirection ret = (Clay_LayoutDirection)ClayLibraryPINVOKE.Clay_LayoutConfig_layoutDirection_get(swigCPtr);
      return ret;
    } 
  }

  public Clay_LayoutConfig() : this(ClayLibraryPINVOKE.new_Clay_LayoutConfig(), true) {
  }

}
