//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum Clay_TextElementConfigWrapMode {
  CLAY_TEXT_WRAP_WORDS,
  CLAY_TEXT_WRAP_NEWLINES,
  CLAY_TEXT_WRAP_NONE
}
