//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Clay__LayoutElementTreeRoot : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Clay__LayoutElementTreeRoot(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Clay__LayoutElementTreeRoot obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Clay__LayoutElementTreeRoot obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Clay__LayoutElementTreeRoot() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ClayLibraryPINVOKE.delete_Clay__LayoutElementTreeRoot(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint layoutElementIndex {
    set {
      ClayLibraryPINVOKE.Clay__LayoutElementTreeRoot_layoutElementIndex_set(swigCPtr, value);
    } 
    get {
      uint ret = ClayLibraryPINVOKE.Clay__LayoutElementTreeRoot_layoutElementIndex_get(swigCPtr);
      return ret;
    } 
  }

  public uint parentId {
    set {
      ClayLibraryPINVOKE.Clay__LayoutElementTreeRoot_parentId_set(swigCPtr, value);
    } 
    get {
      uint ret = ClayLibraryPINVOKE.Clay__LayoutElementTreeRoot_parentId_get(swigCPtr);
      return ret;
    } 
  }

  public uint clipElementId {
    set {
      ClayLibraryPINVOKE.Clay__LayoutElementTreeRoot_clipElementId_set(swigCPtr, value);
    } 
    get {
      uint ret = ClayLibraryPINVOKE.Clay__LayoutElementTreeRoot_clipElementId_get(swigCPtr);
      return ret;
    } 
  }

  public uint zIndex {
    set {
      ClayLibraryPINVOKE.Clay__LayoutElementTreeRoot_zIndex_set(swigCPtr, value);
    } 
    get {
      uint ret = ClayLibraryPINVOKE.Clay__LayoutElementTreeRoot_zIndex_get(swigCPtr);
      return ret;
    } 
  }

  public Clay_Vector2 pointerOffset {
    set {
      ClayLibraryPINVOKE.Clay__LayoutElementTreeRoot_pointerOffset_set(swigCPtr, Clay_Vector2.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay__LayoutElementTreeRoot_pointerOffset_get(swigCPtr);
      Clay_Vector2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_Vector2(cPtr, false);
      return ret;
    } 
  }

  public Clay__LayoutElementTreeRoot() : this(ClayLibraryPINVOKE.new_Clay__LayoutElementTreeRoot(), true) {
  }

}
