//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum Clay_FloatingAttachPointType : byte {
  CLAY_ATTACH_POINT_LEFT_TOP,
  CLAY_ATTACH_POINT_LEFT_CENTER,
  CLAY_ATTACH_POINT_LEFT_BOTTOM,
  CLAY_ATTACH_POINT_CENTER_TOP,
  CLAY_ATTACH_POINT_CENTER_CENTER,
  CLAY_ATTACH_POINT_CENTER_BOTTOM,
  CLAY_ATTACH_POINT_RIGHT_TOP,
  CLAY_ATTACH_POINT_RIGHT_CENTER,
  CLAY_ATTACH_POINT_RIGHT_BOTTOM
}
