//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum Clay__SizeDistributionType {
  CLAY__SIZE_DISTRIBUTION_TYPE_SCROLL_CONTAINER,
  CLAY__SIZE_DISTRIBUTION_TYPE_RESIZEABLE_CONTAINER,
  CLAY__SIZE_DISTRIBUTION_TYPE_GROW_CONTAINER
}
