//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum Clay_RenderCommandType {
  CLAY_RENDER_COMMAND_TYPE_NONE,
  CLAY_RENDER_COMMAND_TYPE_RECTANGLE,
  CLAY_RENDER_COMMAND_TYPE_BORDER,
  CLAY_RENDER_COMMAND_TYPE_TEXT,
  CLAY_RENDER_COMMAND_TYPE_IMAGE,
  CLAY_RENDER_COMMAND_TYPE_SCISSOR_START,
  CLAY_RENDER_COMMAND_TYPE_SCISSOR_END,
  CLAY_RENDER_COMMAND_TYPE_CUSTOM
}
