//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum Clay_PointerDataInteractionState {
  CLAY_POINTER_DATA_PRESSED_THIS_FRAME,
  CLAY_POINTER_DATA_PRESSED,
  CLAY_POINTER_DATA_RELEASED_THIS_FRAME,
  CLAY_POINTER_DATA_RELEASED
}
