//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Clay_SizingAxis : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Clay_SizingAxis(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Clay_SizingAxis obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Clay_SizingAxis obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Clay_SizingAxis() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ClayLibraryPINVOKE.delete_Clay_SizingAxis(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Clay_SizingMinMax sizeMinMax {
    set {
      ClayLibraryPINVOKE.Clay_SizingAxis_sizeMinMax_set(swigCPtr, Clay_SizingMinMax.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay_SizingAxis_sizeMinMax_get(swigCPtr);
      Clay_SizingMinMax ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_SizingMinMax(cPtr, false);
      return ret;
    } 
  }

  public float sizePercent {
    set {
      ClayLibraryPINVOKE.Clay_SizingAxis_sizePercent_set(swigCPtr, value);
    } 
    get {
      float ret = ClayLibraryPINVOKE.Clay_SizingAxis_sizePercent_get(swigCPtr);
      return ret;
    } 
  }

  public Clay__SizingType type {
    set {
      ClayLibraryPINVOKE.Clay_SizingAxis_type_set(swigCPtr, (int)value);
    } 
    get {
      Clay__SizingType ret = (Clay__SizingType)ClayLibraryPINVOKE.Clay_SizingAxis_type_get(swigCPtr);
      return ret;
    } 
  }

  public Clay_SizingAxis() : this(ClayLibraryPINVOKE.new_Clay_SizingAxis(), true) {
  }

}
