//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum Clay_LayoutAlignmentY : byte {
  CLAY_ALIGN_Y_TOP,
  CLAY_ALIGN_Y_BOTTOM,
  CLAY_ALIGN_Y_CENTER
}
