//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Clay_TextElementConfig : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Clay_TextElementConfig(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Clay_TextElementConfig obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Clay_TextElementConfig obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Clay_TextElementConfig() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ClayLibraryPINVOKE.delete_Clay_TextElementConfig(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Clay_Color textColor {
    set {
      ClayLibraryPINVOKE.Clay_TextElementConfig_textColor_set(swigCPtr, Clay_Color.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay_TextElementConfig_textColor_get(swigCPtr);
      Clay_Color ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_Color(cPtr, false);
      return ret;
    } 
  }

  public ushort fontId {
    set {
      ClayLibraryPINVOKE.Clay_TextElementConfig_fontId_set(swigCPtr, value);
    } 
    get {
      ushort ret = ClayLibraryPINVOKE.Clay_TextElementConfig_fontId_get(swigCPtr);
      return ret;
    } 
  }

  public ushort fontSize {
    set {
      ClayLibraryPINVOKE.Clay_TextElementConfig_fontSize_set(swigCPtr, value);
    } 
    get {
      ushort ret = ClayLibraryPINVOKE.Clay_TextElementConfig_fontSize_get(swigCPtr);
      return ret;
    } 
  }

  public ushort letterSpacing {
    set {
      ClayLibraryPINVOKE.Clay_TextElementConfig_letterSpacing_set(swigCPtr, value);
    } 
    get {
      ushort ret = ClayLibraryPINVOKE.Clay_TextElementConfig_letterSpacing_get(swigCPtr);
      return ret;
    } 
  }

  public ushort lineHeight {
    set {
      ClayLibraryPINVOKE.Clay_TextElementConfig_lineHeight_set(swigCPtr, value);
    } 
    get {
      ushort ret = ClayLibraryPINVOKE.Clay_TextElementConfig_lineHeight_get(swigCPtr);
      return ret;
    } 
  }

  public Clay_TextElementConfigWrapMode wrapMode {
    set {
      ClayLibraryPINVOKE.Clay_TextElementConfig_wrapMode_set(swigCPtr, (int)value);
    } 
    get {
      Clay_TextElementConfigWrapMode ret = (Clay_TextElementConfigWrapMode)ClayLibraryPINVOKE.Clay_TextElementConfig_wrapMode_get(swigCPtr);
      return ret;
    } 
  }

  public Clay_TextElementConfig() : this(ClayLibraryPINVOKE.new_Clay_TextElementConfig(), true) {
  }

}
