//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Clay_ScrollContainerData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Clay_ScrollContainerData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Clay_ScrollContainerData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Clay_ScrollContainerData obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Clay_ScrollContainerData() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ClayLibraryPINVOKE.delete_Clay_ScrollContainerData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Clay_Vector2 scrollPosition {
    set {
      ClayLibraryPINVOKE.Clay_ScrollContainerData_scrollPosition_set(swigCPtr, Clay_Vector2.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay_ScrollContainerData_scrollPosition_get(swigCPtr);
      Clay_Vector2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_Vector2(cPtr, false);
      return ret;
    } 
  }

  public Clay_Dimensions scrollContainerDimensions {
    set {
      ClayLibraryPINVOKE.Clay_ScrollContainerData_scrollContainerDimensions_set(swigCPtr, Clay_Dimensions.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay_ScrollContainerData_scrollContainerDimensions_get(swigCPtr);
      Clay_Dimensions ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_Dimensions(cPtr, false);
      return ret;
    } 
  }

  public Clay_Dimensions contentDimensions {
    set {
      ClayLibraryPINVOKE.Clay_ScrollContainerData_contentDimensions_set(swigCPtr, Clay_Dimensions.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay_ScrollContainerData_contentDimensions_get(swigCPtr);
      Clay_Dimensions ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_Dimensions(cPtr, false);
      return ret;
    } 
  }

  public Clay_ScrollElementConfig config {
    set {
      ClayLibraryPINVOKE.Clay_ScrollContainerData_config_set(swigCPtr, Clay_ScrollElementConfig.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay_ScrollContainerData_config_get(swigCPtr);
      Clay_ScrollElementConfig ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_ScrollElementConfig(cPtr, false);
      return ret;
    } 
  }

  public bool found {
    set {
      ClayLibraryPINVOKE.Clay_ScrollContainerData_found_set(swigCPtr, value);
    } 
    get {
      bool ret = ClayLibraryPINVOKE.Clay_ScrollContainerData_found_get(swigCPtr);
      return ret;
    } 
  }

  public Clay_ScrollContainerData() : this(ClayLibraryPINVOKE.new_Clay_ScrollContainerData(), true) {
  }

}
