//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Clay__LayoutElementTreeNode : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Clay__LayoutElementTreeNode(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Clay__LayoutElementTreeNode obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Clay__LayoutElementTreeNode obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Clay__LayoutElementTreeNode() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ClayLibraryPINVOKE.delete_Clay__LayoutElementTreeNode(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Clay_LayoutElement layoutElement {
    set {
      ClayLibraryPINVOKE.Clay__LayoutElementTreeNode_layoutElement_set(swigCPtr, Clay_LayoutElement.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay__LayoutElementTreeNode_layoutElement_get(swigCPtr);
      Clay_LayoutElement ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_LayoutElement(cPtr, false);
      return ret;
    } 
  }

  public Clay_Vector2 position {
    set {
      ClayLibraryPINVOKE.Clay__LayoutElementTreeNode_position_set(swigCPtr, Clay_Vector2.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay__LayoutElementTreeNode_position_get(swigCPtr);
      Clay_Vector2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_Vector2(cPtr, false);
      return ret;
    } 
  }

  public Clay_Vector2 nextChildOffset {
    set {
      ClayLibraryPINVOKE.Clay__LayoutElementTreeNode_nextChildOffset_set(swigCPtr, Clay_Vector2.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ClayLibraryPINVOKE.Clay__LayoutElementTreeNode_nextChildOffset_get(swigCPtr);
      Clay_Vector2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new Clay_Vector2(cPtr, false);
      return ret;
    } 
  }

  public Clay__LayoutElementTreeNode() : this(ClayLibraryPINVOKE.new_Clay__LayoutElementTreeNode(), true) {
  }

}
